"""Studio curated templates: API backends (FastAPI + SQLite, Express + JSON store)."""

FASTAPI_API = {
    "id": "fastapi-api",
    "name": "FastAPI Service",
    "description": "Python FastAPI JSON API with a SQLite task store — ready for uvicorn.",
    "stack": "fastapi",
    "files": [
        {
            "path": "main.py",
            "content": '''"""Task API generated by StarWaves Studio (FastAPI + SQLite)."""

import sqlite3
from contextlib import asynccontextmanager
from datetime import datetime, timezone

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

DB_PATH = "tasks.db"


def init_db() -> None:
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                done INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL
            )
            """
        )


@asynccontextmanager
async def lifespan(_: FastAPI):
    init_db()
    yield


app = FastAPI(title="Studio Task API", lifespan=lifespan)


class TaskCreate(BaseModel):
    title: str = Field(min_length=1, max_length=200)


class TaskUpdate(BaseModel):
    done: bool


def _row_to_task(row) -> dict:
    return {"id": row[0], "title": row[1], "done": bool(row[2]), "created_at": row[3]}


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/tasks")
def list_tasks():
    with sqlite3.connect(DB_PATH) as conn:
        rows = conn.execute("SELECT id, title, done, created_at FROM tasks ORDER BY id").fetchall()
    return {"tasks": [_row_to_task(row) for row in rows]}


@app.post("/tasks", status_code=201)
def create_task(body: TaskCreate):
    now = datetime.now(timezone.utc).isoformat()
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute(
            "INSERT INTO tasks (title, done, created_at) VALUES (?, 0, ?)",
            (body.title, now),
        )
        task_id = cursor.lastrowid
        conn.commit()
    return {"id": task_id, "title": body.title, "done": False, "created_at": now}


@app.patch("/tasks/{task_id}")
def update_task(task_id: int, body: TaskUpdate):
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("UPDATE tasks SET done = ? WHERE id = ?", (int(body.done), task_id))
        conn.commit()
        if cursor.rowcount == 0:
            raise HTTPException(status_code=404, detail="Task not found")
    return {"id": task_id, "done": body.done}


@app.delete("/tasks/{task_id}", status_code=204)
def delete_task(task_id: int):
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("DELETE FROM tasks WHERE id = ?", (task_id,))
        conn.commit()
        if cursor.rowcount == 0:
            raise HTTPException(status_code=404, detail="Task not found")
''',
        },
        {
            "path": "requirements.txt",
            "content": """fastapi>=0.115
uvicorn[standard]>=0.30
pydantic>=2.7
""",
        },
        {
            "path": "README.md",
            "content": """# Studio Task API

FastAPI + SQLite service generated by StarWaves Studio.

```bash
pip install -r requirements.txt
uvicorn main:app --reload
```

Endpoints: `GET /health`, `GET /tasks`, `POST /tasks`, `PATCH /tasks/{id}`, `DELETE /tasks/{id}`.
""",
        },
    ],
}

NODE_EXPRESS_API = {
    "id": "node-express-api",
    "name": "Express JSON API",
    "description": "Node.js + Express REST API with a file-backed JSON note store.",
    "stack": "node-express",
    "files": [
        {
            "path": "package.json",
            "content": """{
  "name": "studio-api",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "node --watch server.js"
  },
  "dependencies": {
    "express": "^5.1.0"
  }
}
""",
        },
        {
            "path": "server.js",
            "content": """import express from 'express'
import { readFile, writeFile } from 'node:fs/promises'

const PORT = process.env.PORT || 3000
const DB_FILE = 'notes.json'

const app = express()
app.use(express.json())

async function readNotes() {
  try {
    return JSON.parse(await readFile(DB_FILE, 'utf-8'))
  } catch {
    return []
  }
}

async function writeNotes(notes) {
  await writeFile(DB_FILE, JSON.stringify(notes, null, 2))
}

app.get('/health', (_req, res) => res.json({ status: 'ok' }))

app.get('/notes', async (_req, res) => {
  res.json({ notes: await readNotes() })
})

app.post('/notes', async (req, res) => {
  const { title, body } = req.body ?? {}
  if (!title) return res.status(400).json({ error: 'title is required' })
  const notes = await readNotes()
  const note = { id: Date.now(), title, body: body ?? '', createdAt: new Date().toISOString() }
  notes.push(note)
  await writeNotes(notes)
  res.status(201).json(note)
})

app.delete('/notes/:id', async (req, res) => {
  const notes = await readNotes()
  const next = notes.filter((n) => String(n.id) !== req.params.id)
  if (next.length === notes.length) return res.status(404).json({ error: 'note not found' })
  await writeNotes(next)
  res.status(204).end()
})

app.listen(PORT, () => console.log(`Studio API listening on :${PORT}`))
""",
        },
        {
            "path": ".gitignore",
            "content": """node_modules
notes.json
.env
""",
        },
        {
            "path": "README.md",
            "content": """# Studio API

Express REST API generated by StarWaves Studio.

```bash
npm install
npm run dev
```

Endpoints: `GET /health`, `GET /notes`, `POST /notes`, `DELETE /notes/:id`.
""",
        },
    ],
}

API_TEMPLATES = [FASTAPI_API, NODE_EXPRESS_API]
