"""Studio curated templates: web starters (React + Vite, static site)."""

REACT_VITE = {
    "id": "react-vite",
    "name": "React + Vite App",
    "description": "Modern React 19 single-page app scaffolded with Vite and a clean monochrome base.",
    "stack": "react-vite",
    "files": [
        {
            "path": "package.json",
            "content": """{
  "name": "studio-app",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.1.0",
    "react-dom": "^19.1.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.5.0",
    "vite": "^6.3.5"
  }
}
""",
        },
        {
            "path": "vite.config.js",
            "content": """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
""",
        },
        {
            "path": "index.html",
            "content": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Studio App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
""",
        },
        {
            "path": "src/main.jsx",
            "content": """import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
""",
        },
        {
            "path": "src/App.jsx",
            "content": """import { useState } from 'react'

export default function App() {
  const [count, setCount] = useState(0)

  return (
    <main className="app">
      <h1>Studio App</h1>
      <p>Edit <code>src/App.jsx</code> and save to hot-reload.</p>
      <button onClick={() => setCount((c) => c + 1)}>Count: {count}</button>
    </main>
  )
}
""",
        },
        {
            "path": "src/index.css",
            "content": """:root {
  color-scheme: light dark;
  font-family: system-ui, -apple-system, sans-serif;
}

body {
  margin: 0;
  min-height: 100vh;
  background: #fafafa;
  color: #18181b;
}

.app {
  max-width: 720px;
  margin: 0 auto;
  padding: 4rem 1.5rem;
  display: grid;
  gap: 1rem;
  justify-items: start;
}

button {
  padding: 0.6rem 1.2rem;
  border-radius: 8px;
  border: 1px solid #27272a;
  background: #18181b;
  color: #fff;
  cursor: pointer;
}
""",
        },
        {
            "path": ".gitignore",
            "content": """node_modules
dist
.env
.env.*
!.env.example
""",
        },
        {
            "path": "README.md",
            "content": """# Studio App

React + Vite app generated by StarWaves Studio.

```bash
npm install
npm run dev     # local dev server
npm run build   # production build to dist/
```
""",
        },
    ],
}

STATIC_SITE = {
    "id": "static-site",
    "name": "Static Website",
    "description": "Zero-build HTML/CSS/JS website — perfect for landing pages, portfolios, and blogs.",
    "stack": "html-css-js",
    "files": [
        {
            "path": "index.html",
            "content": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Website</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <header class="hero">
      <h1>Hello from Studio</h1>
      <p>A static website generated by StarWaves Studio.</p>
      <button id="cta" type="button">Get started</button>
    </header>
    <script src="script.js"></script>
  </body>
</html>
""",
        },
        {
            "path": "styles.css",
            "content": """* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background: #fafafa;
  color: #18181b;
}

.hero {
  min-height: 100vh;
  display: grid;
  place-content: center;
  gap: 1rem;
  text-align: center;
  padding: 2rem;
}

#cta {
  justify-self: center;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 8px;
  background: #18181b;
  color: #fff;
  cursor: pointer;
}
""",
        },
        {
            "path": "script.js",
            "content": """document.getElementById('cta')?.addEventListener('click', () => {
  document.querySelector('.hero p').textContent = 'You are all set. Start building!'
})
""",
        },
        {
            "path": "README.md",
            "content": """# Static Website

Plain HTML/CSS/JS site generated by StarWaves Studio. No build step required —
open the preview directly or deploy anywhere static files are served.
""",
        },
    ],
}

WEB_TEMPLATES = [REACT_VITE, STATIC_SITE]
