import { ChevronDown, ChevronUp, Circle, Pause, Play, Plus, SkipBack, SkipForward, Square, Trash2 } from 'lucide-react'
import { keyframesForNode } from './animationModel'

function KeyframeButton({ keyframe, endFrame, selected, onSelect, onDelete }) {
  const position = `${Math.max(0, Math.min(100, (keyframe.frame / Math.max(1, endFrame)) * 100))}%`
  return <button type="button" className={`modeling-track-key ${selected ? 'is-selected' : ''}`} style={{ left: position }} onClick={() => onSelect(keyframe)} onDoubleClick={() => onDelete(keyframe)} aria-label={`Keyframe at frame ${keyframe.frame}`} title={`Frame ${keyframe.frame} · double-click to delete`}><span /></button>
}

export function StudioTimeline({ nodes, scene, importedClips = [], playing, currentFrame, selectedKeyframe, collapsed, onTogglePlayback, onStop, onFrameChange, onAddKeyframe, onDeleteKeyframe, onSelectKeyframe, onFpsChange, onLoopChange, onToggleCollapse }) {
  const endFrame = Number(scene.timeline?.endFrame || 120)
  const fps = Number(scene.timeline?.fps || 24)
  const clips = [...(scene.animations || []), ...importedClips.map((clip) => ({ ...clip, imported: true, tracks: [] }))]
  return <section className={`modeling-timeline ${collapsed ? 'is-collapsed' : ''}`} aria-label="Animation timeline">
    <div className="modeling-timeline-header"><div className="modeling-browser-tabs" role="tablist"><button type="button" className="is-active">Timeline</button><button type="button" disabled>Dope Sheet</button><button type="button" disabled>Graph Editor</button></div><div className="modeling-timeline-meta"><label>FPS <input type="number" min="1" max="120" value={fps} onChange={(event) => onFpsChange?.(event.target.value)} /></label><label className="modeling-loop-toggle"><input type="checkbox" checked={scene.timeline?.loop !== false} onChange={(event) => onLoopChange?.(event.target.checked)} /> Loop</label><button type="button" className="modeling-timeline-collapse" onClick={onToggleCollapse} aria-label={collapsed ? 'Expand timeline' : 'Collapse timeline'}>{collapsed ? <ChevronUp size={14} /> : <ChevronDown size={14} />}</button></div><div className="modeling-timeline-actions"><button type="button" onClick={() => onFrameChange(scene.timeline?.startFrame || 0)} aria-label="Go to first frame"><SkipBack size={14} /></button><button type="button" onClick={() => onFrameChange(Math.max(0, currentFrame - 1))} aria-label="Previous frame"><SkipBack size={12} /></button><button type="button" onClick={onTogglePlayback} aria-label={playing ? 'Pause animation' : 'Play animation'}>{playing ? <Pause size={14} /> : <Play size={14} />}</button><button type="button" onClick={onStop} aria-label="Stop animation"><Square size={12} /></button><button type="button" onClick={() => onFrameChange(Math.min(endFrame, currentFrame + 1))} aria-label="Next frame"><SkipForward size={12} /></button><button type="button" className="modeling-keyframe-button" onClick={onAddKeyframe}><Plus size={13} /> Keyframe</button>{selectedKeyframe && <button type="button" className="modeling-icon-button" onClick={onDeleteKeyframe} aria-label="Delete selected keyframe"><Trash2 size={13} /></button>}</div></div>
    {!collapsed && <><div className="modeling-timeline-body"><div className="modeling-timeline-labels">{nodes.slice(0, 12).map((node) => <div key={node.id}><ChevronDown size={11} /><Circle size={8} />{node.name}</div>)}{nodes.length === 0 && <p className="modeling-muted-copy">Animation tracks appear when a model is loaded.</p>}</div><div className="modeling-timeline-grid"><div className="modeling-frame-ruler">{[0, 20, 40, 60, 80, 100, endFrame].map((frame, index) => <button type="button" key={`${frame}-${index}`} onClick={() => onFrameChange(frame)}>{frame}</button>)}</div>{nodes.slice(0, 12).map((node) => <div className="modeling-track-row" key={node.id}>{keyframesForNode(scene, node.id).map((keyframe) => <KeyframeButton key={`${keyframe.clipId}-${keyframe.frame}`} keyframe={keyframe} endFrame={endFrame} selected={selectedKeyframe?.clipId === keyframe.clipId && selectedKeyframe?.nodeId === node.id && selectedKeyframe?.frame === keyframe.frame} onSelect={onSelectKeyframe} onDelete={onDeleteKeyframe} />)}</div>)}</div></div><label className="modeling-frame-slider"><span>Frame {currentFrame}</span><input type="range" min={scene.timeline?.startFrame || 0} max={endFrame} value={currentFrame} onChange={(event) => onFrameChange(Number(event.target.value))} aria-label="Current animation frame" /></label><small className="modeling-timeline-note">{clips.length} animation clip{clips.length === 1 ? '' : 's'} · double-click a keyframe to delete it.</small></>}
  </section>
}
