import { Box, ChevronDown, CircleDot, Paintbrush, Rotate3d, Scaling, SlidersHorizontal } from 'lucide-react'

function VectorInput({ label, values, onChange }) {
  return <div className="modeling-vector-input"><span>{label}</span>{['X', 'Y', 'Z'].map((axis, index) => <label key={axis}><em>{axis}</em><input type="number" step="0.01" value={Number(values?.[index] ?? (label === 'Scale' ? 1 : 0)).toFixed(2)} onChange={(event) => { const next = [...(values || [0, 0, 0])]; next[index] = Number(event.target.value); onChange(next) }} aria-label={`${label} ${axis}`} /></label>)}</div>
}

function PropertySection({ icon, title, children, open = false }) {
  return <details open={open}><summary>{icon}{title}<ChevronDown size={13} /></summary><div className="modeling-property-body">{children}</div></details>
}

export function StudioProperties({ node, capabilities, currentFrame, paintSettings, onPaintSettingsChange, onActivatePaint, onUpdateNode, onDuplicateNode, onDeleteNode, onMaterialChange }) {
  if (!node) return <section className="modeling-properties"><div className="modeling-panel-heading compact"><div><span className="modeling-panel-kicker">Properties</span><h2>Inspector</h2></div><SlidersHorizontal size={16} /></div><div className="modeling-inspector-empty"><CircleDot size={22} /><p>Select an object</p><small>Choose an object in the viewport or Outliner to edit its properties.</small></div></section>
  return <section className="modeling-properties" aria-label="Object properties">
    <div className="modeling-panel-heading compact"><div><span className="modeling-panel-kicker">Properties</span><h2>{node.name}</h2></div><Box size={16} /></div>
    <PropertySection icon={<Rotate3d size={14} />} title="Transform" open>
      <VectorInput label="Position" values={node.position} onChange={(value) => onUpdateNode({ position: value })} />
      <VectorInput label="Rotation" values={node.rotation} onChange={(value) => onUpdateNode({ rotation: value })} />
      <VectorInput label="Scale" values={node.scale} onChange={(value) => onUpdateNode({ scale: value })} />
    </PropertySection>
    <PropertySection icon={<CircleDot size={14} />} title="Appearance" open>
      {capabilities?.materials && node.materialColor ? <label className="modeling-property-row"><span>Base color</span><input type="color" value={node.materialColor} onChange={(event) => { onUpdateNode({ materialColor: event.target.value }); onMaterialChange?.({ color: event.target.value }) }} /></label> : <p className="modeling-muted-copy">This object has no editable material.</p>}
      {capabilities?.materials && <><label className="modeling-property-row"><span>Metalness</span><input type="range" min="0" max="1" step="0.01" value={node.metalness ?? 0} onChange={(event) => { const value = Number(event.target.value); onUpdateNode({ metalness: value }); onMaterialChange?.({ metalness: value }) }} /><output>{Number(node.metalness ?? 0).toFixed(2)}</output></label><label className="modeling-property-row"><span>Roughness</span><input type="range" min="0" max="1" step="0.01" value={node.roughness ?? 0.5} onChange={(event) => { const value = Number(event.target.value); onUpdateNode({ roughness: value }); onMaterialChange?.({ roughness: value }) }} /><output>{Number(node.roughness ?? 0.5).toFixed(2)}</output></label><label className="modeling-property-row"><span>Opacity</span><input type="range" min="0" max="1" step="0.01" value={node.opacity ?? 1} onChange={(event) => { const value = Number(event.target.value); onUpdateNode({ opacity: value }); onMaterialChange?.({ opacity: value }) }} /><output>{Number(node.opacity ?? 1).toFixed(2)}</output></label></>}
      {capabilities?.texturePaint ? <div className="modeling-paint-controls"><div className="modeling-paint-heading"><span><Paintbrush size={13} /> Texture paint</span><button type="button" className="modeling-secondary-button" onClick={onActivatePaint}>Activate</button></div><label className="modeling-property-row"><span>Brush size</span><input type="range" min="1" max="100" value={paintSettings?.size || 24} onChange={(event) => onPaintSettingsChange?.({ ...paintSettings, size: Number(event.target.value) })} /><output>{paintSettings?.size || 24}</output></label><label className="modeling-property-row"><span>Strength</span><input type="range" min="0.05" max="1" step="0.05" value={paintSettings?.strength || 0.8} onChange={(event) => onPaintSettingsChange?.({ ...paintSettings, strength: Number(event.target.value) })} /><output>{Number(paintSettings?.strength || 0.8).toFixed(2)}</output></label><label className="modeling-property-row"><span>Color</span><input type="color" value={paintSettings?.color || '#a83b59'} onChange={(event) => onPaintSettingsChange?.({ ...paintSettings, color: event.target.value, mode: 'paint' })} /><button type="button" className="modeling-secondary-button" onClick={() => onPaintSettingsChange?.({ ...paintSettings, mode: paintSettings?.mode === 'erase' ? 'paint' : 'erase' })}>{paintSettings?.mode === 'erase' ? 'Erase on' : 'Erase'}</button></label></div> : <p className="modeling-muted-copy">Texture paint needs a mesh with UV coordinates and a paintable material.</p>}
    </PropertySection>
    <PropertySection icon={<Scaling size={14} />} title="Rig"><p className="modeling-muted-copy">Rig and bone constraints are read-only until a compatible rig is detected.</p></PropertySection>
    <PropertySection icon={<Rotate3d size={14} />} title="Animation"><p className="modeling-muted-copy">Frame {currentFrame}. Add a transform keyframe from the timeline.</p></PropertySection>
    <PropertySection icon={<Box size={14} />} title="Advanced"><div className="modeling-property-actions"><button type="button" className="modeling-secondary-button" onClick={onDuplicateNode}>Duplicate</button><button type="button" className="modeling-secondary-button" onClick={onDeleteNode}>Delete</button></div><label className="modeling-property-row modeling-property-name"><span>Name</span><input value={node.name} onChange={(event) => onUpdateNode({ name: event.target.value })} /></label><p className="modeling-muted-copy">Type: {node.type} · Parent: {node.parentId || 'Scene'}</p></PropertySection>
  </section>
}
