import { Bell, Bot, BriefcaseBusiness, Files, FolderKanban, LogOut, Moon, PhoneCall, PlusCircle } from 'lucide-react'

export const ACTIONS_ITEMS = [
  {
    id: 'action-create-todo',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Create New Task',
    subtitle: 'Quickly add a new item to your todo list',
    badge: 'Action',
    actionId: 'create-todo',
    icon: PlusCircle,
    keywords: ['new task', 'add todo', 'create task', 'new todo', 'add item'],
  },
  {
    id: 'action-create-project',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Add New Project',
    subtitle: 'Start a new project with lifecycle tracking and repository linking',
    badge: 'Action',
    actionId: 'create-project',
    icon: FolderKanban,
    keywords: ['new project', 'add project', 'start repo', 'create project'],
  },
  {
    id: 'action-create-job',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Log Job Application',
    subtitle: 'Track a new job application, company, role, and interview timeline',
    badge: 'Action',
    actionId: 'create-job',
    icon: BriefcaseBusiness,
    keywords: ['log job', 'new application', 'apply job', 'job tracker', 'add job'],
  },
  {
    id: 'action-create-document',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Create New Document',
    subtitle: 'Start a new markdown document, spec, or notes page',
    badge: 'Action',
    actionId: 'create-document',
    icon: Files,
    keywords: ['new document', 'add doc', 'new note', 'create note', 'write'],
  },
  {
    id: 'action-new-eve-chat',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'New Eve AI Chat Session',
    subtitle: 'Start a clean chat conversation with Eve AI Assistant',
    badge: 'Action',
    actionId: 'new-eve-chat',
    icon: Bot,
    keywords: ['new chat', 'fresh session', 'reset eve', 'clear chat', 'ask ai'],
  },
  {
    id: 'action-open-eve',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Open Eve Assistant Drawer',
    subtitle: 'Launch the Eve AI assistant quick drawer from anywhere',
    badge: 'Action',
    actionId: 'open-eve',
    icon: Bot,
    keywords: ['open eve', 'eve drawer', 'assistant popup', 'ask eve'],
  },
  {
    id: 'action-call-eve',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Start Voice Call with Eve',
    subtitle: 'Instantly initiate a live voice session with Eve AI',
    badge: 'Action',
    actionId: 'call-eve',
    icon: PhoneCall,
    keywords: ['call eve', 'voice chat', 'speak to ai', 'voice call', 'eve talk'],
  },
  {
    id: 'action-toggle-theme',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Toggle Dark / Light Theme',
    subtitle: 'Switch interface between dark and light monochrome modes',
    badge: 'Action',
    actionId: 'toggle-theme',
    icon: Moon,
    keywords: ['toggle theme', 'dark mode', 'light mode', 'switch theme', 'night mode'],
  },
  {
    id: 'action-open-notifications',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'View Notifications',
    subtitle: 'Open the notifications drawer and check alerts',
    badge: 'Action',
    actionId: 'open-notifications',
    icon: Bell,
    keywords: ['notifications', 'alerts', 'inbox', 'unread', 'messages'],
  },
  {
    id: 'action-sign-out',
    type: 'action',
    category: 'actions',
    group: 'Quick Actions',
    title: 'Sign Out',
    subtitle: 'Log out of current StarWaves session',
    badge: 'Action',
    actionId: 'sign-out',
    icon: LogOut,
    keywords: ['logout', 'sign out', 'disconnect', 'leave', 'exit'],
  },
]
