import { Bot, Brain, CalendarClock, History, PhoneCall } from 'lucide-react'

export const EVE_PAGES_ITEMS = [
  {
    id: 'page-eve-chat',
    type: 'page',
    category: 'eve',
    group: 'Eve AI Assistant',
    title: 'Eve AI Chat',
    subtitle: 'Intelligent AI assistant powered by OpenAI, Anthropic & Gemini',
    badge: 'Eve AI > Chat',
    page: 'eve',
    icon: Bot,
    keywords: ['assistant', 'ai', 'chat', 'llm', 'gpt', 'claude', 'gemini', 'prompts', 'eve'],
  },
  {
    id: 'page-eve-sessions',
    type: 'page',
    category: 'eve',
    group: 'Eve AI Assistant',
    title: 'Eve Chat Sessions',
    subtitle: 'Browse past AI conversations and preserved chat histories',
    badge: 'Eve AI > Sessions',
    page: 'eve-sessions',
    icon: History,
    keywords: ['conversations', 'history', 'saved chats', 'archive', 'sessions'],
  },
  {
    id: 'page-eve-memory',
    type: 'page',
    category: 'eve',
    group: 'Eve AI Assistant',
    title: 'Eve Long-Term Memory',
    subtitle: 'Facts, learned user preferences, and persistent workspace context',
    badge: 'Eve AI > Memory',
    page: 'eve-memory',
    icon: Brain,
    keywords: ['facts', 'knowledge', 'preferences', 'context', 'memory', 'recall'],
  },
  {
    id: 'page-eve-call',
    type: 'page',
    category: 'eve',
    group: 'Eve AI Assistant',
    title: 'Eve Voice & AI Call',
    subtitle: 'Real-time bidirectional voice conversation with Eve AI',
    badge: 'Eve AI > Voice Call',
    page: 'eve-call',
    icon: PhoneCall,
    keywords: ['voice', 'speech', 'webrtc', 'call', 'talk', 'mic', 'groq', 'audio'],
  },
  {
    id: 'page-eve-schedules',
    type: 'page',
    category: 'eve',
    group: 'Eve AI Assistant',
    title: 'Eve Schedules & Reminders',
    subtitle: 'Automated background cron & one-time prompts and voice call triggers',
    badge: 'Eve AI > Schedules',
    page: 'eve-schedules',
    icon: CalendarClock,
    keywords: ['cron', 'recurring', 'reminders', 'timers', 'automated', 'schedule'],
  },
]
