import {
  AppWindow,
  Blocks,
  BriefcaseBusiness,
  CalendarDays,
  ChartNoAxesCombined,
  Contact,
  Files,
  FolderKanban,
  LayoutDashboard,
  LayoutTemplate,
  ListTodo,
  Mail,
  MessageCircle,
  MessageSquare,
  Palette,
  Phone,
  Rocket,
  Settings,
  SquareTerminal,
  Trophy,
  UserRound,
} from 'lucide-react'

export const PAGES_ITEMS = [
  {
    id: 'page-dashboard',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Dashboard',
    subtitle: 'Workspace overview, daily planner, quick metrics & widgets',
    badge: 'Home > Dashboard',
    page: 'dashboard',
    icon: LayoutDashboard,
    keywords: ['home', 'overview', 'summary', 'widgets', 'daily', 'planner', 'metrics'],
  },
  {
    id: 'page-todo',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Todo List',
    subtitle: 'Task management, priorities, deadlines, and task checklist',
    badge: 'Code > Todo',
    page: 'todo',
    icon: ListTodo,
    keywords: ['tasks', 'todos', 'checklist', 'actions', 'done', 'pending', 'priority'],
  },
  {
    id: 'page-projects',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Projects',
    subtitle: 'Active projects, repositories, lifecycle pipelines, and milestones',
    badge: 'Code > Projects',
    page: 'projects',
    icon: FolderKanban,
    keywords: ['kanban', 'repos', 'git', 'lifecycle', 'idea', 'build', 'ship', 'code'],
  },
  {
    id: 'page-documents',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Documents',
    subtitle: 'Notes, technical specs, markdown editor, and project documents',
    badge: 'Code > Documents',
    page: 'documents',
    icon: Files,
    keywords: ['docs', 'notes', 'markdown', 'wiki', 'specs', 'writing', 'files'],
  },
  {
    id: 'page-workspace',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Workspace Files',
    subtitle: 'Code workspace, Monaco editor, file tree & embedded terminal',
    badge: 'Code > Workspace',
    page: 'workspace',
    icon: SquareTerminal,
    keywords: ['editor', 'monaco', 'terminal', 'tree', 'code', 'filesystem', 'ide'],
  },
  {
    id: 'page-studio',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Studio',
    subtitle: 'Eve Builder — describe an app, approve the plan, Eve builds it',
    badge: 'Create > Projects',
    page: 'studio',
    icon: Blocks,
    keywords: ['builder', 'build app', 'website', 'generate', 'scaffold', 'eve build', 'no-code', 'fullstack'],
  },
  {
    id: 'page-studio-apps',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Studio Apps',
    subtitle: 'Apps Eve finished building — reopen or run them anytime',
    badge: 'Create > Apps',
    page: 'studio-apps',
    icon: AppWindow,
    keywords: ['apps', 'built apps', 'old apps', 'my apps', 'gallery', 'run app', 'preview', 'launch'],
  },
  {
    id: 'page-studio-templates',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Studio Templates',
    subtitle: 'Curated starters and your published reusable project templates',
    badge: 'Create > Templates',
    page: 'studio-templates',
    icon: LayoutTemplate,
    keywords: ['starter', 'template', 'boilerplate', 'remix', 'react', 'fastapi', 'saas'],
  },
  {
    id: 'page-compete',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Compete',
    subtitle: 'Contest radar and coding stats — Codeforces, LeetCode, heatmaps & velocity',
    badge: 'Evolve > Compete',
    page: 'compete',
    icon: Trophy,
    keywords: ['leetcode', 'codeforces', 'codechef', 'contests', 'problems', 'dsa', 'rating', 'analytics', 'metrics', 'heatmap', 'performance'],
  },
  {
    id: 'page-hackathons',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Hackathons',
    subtitle: 'Hackathon discovery, submission deadlines, prizes, and teams',
    badge: 'Create > Hackathons',
    page: 'hackathons',
    icon: Rocket,
    keywords: ['devpost', 'unstop', 'mlh', 'devfolio', 'prizes', 'events', 'competitions'],
  },
  {
    id: 'page-jobs',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Job Tracker',
    subtitle: 'Job application pipeline, resume tracker, status & interview log',
    badge: 'Create > Jobs',
    page: 'jobs',
    icon: BriefcaseBusiness,
    keywords: ['applications', 'interviews', 'careers', 'offers', 'resume', 'companies'],
  },
  {
    id: 'page-calendar',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Calendar',
    subtitle: 'Daily agenda, Google Calendar events, ICS schedules & reminders',
    badge: 'Connect > Calendar',
    page: 'calendar',
    icon: CalendarDays,
    keywords: ['agenda', 'schedule', 'google calendar', 'events', 'deadlines', 'ics'],
  },
  {
    id: 'page-mails',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Mail',
    subtitle: 'Gmail inbox, messages, category tabs (Primary, Promotions, Updates)',
    badge: 'Connect > Mail',
    page: 'mails',
    icon: Mail,
    keywords: ['gmail', 'inbox', 'emails', 'messages', 'google mail'],
  },
  {
    id: 'page-whatsapp',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'WhatsApp',
    subtitle: 'Multi-device WhatsApp web bridge, chats, messages & reactions',
    badge: 'Connect > WhatsApp',
    page: 'whatsapp',
    icon: MessageCircle,
    keywords: ['whatsapp', 'chats', 'messages', 'qr', 'pairing', 'contacts'],
  },
  {
    id: 'page-chats',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Team Chats',
    subtitle: 'Peer-to-peer workspace chats and real-time team messaging',
    badge: 'Connect > Team Chats',
    page: 'chats',
    icon: MessageSquare,
    keywords: ['direct messages', 'dm', 'chat', 'team'],
  },
  {
    id: 'page-calls',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Calls',
    subtitle: 'WebRTC voice & video calls, dialing directory, and call history',
    badge: 'Connect > Calls',
    page: 'calls',
    icon: Phone,
    keywords: ['video call', 'voice call', 'webrtc', 'dialer', 'phone', 'ring'],
  },
  {
    id: 'page-contacts',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Contacts',
    subtitle: 'Address book, Google Contacts sync, email and phone directory',
    badge: 'Connect > Contacts',
    page: 'contacts',
    icon: Contact,
    keywords: ['address book', 'phonebook', 'google contacts', 'people', 'directory'],
  },
  {
    id: 'page-profile',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Profile',
    subtitle: 'User details, display name, account credentials and role',
    badge: 'You > Profile',
    page: 'profile',
    icon: UserRound,
    keywords: ['user', 'profile', 'avatar', 'name', 'account', 'identity'],
  },
  {
    id: 'page-themes',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Themes & Appearance',
    subtitle: 'Monochrome theme customizer, font presets, radius & density',
    badge: 'You > Themes',
    page: 'themes',
    icon: Palette,
    keywords: ['appearance', 'customizer', 'fonts', 'styling', 'dark mode', 'radius', 'monochrome'],
  },
  {
    id: 'page-setting',
    type: 'page',
    category: 'settings',
    group: 'Pages & Views',
    title: 'Settings',
    subtitle: 'Global workspace settings, connected integrations, and accounts',
    badge: 'You > Settings',
    page: 'setting',
    icon: Settings,
    keywords: ['configuration', 'preferences', 'options', 'setup', 'integrations'],
  },
  {
    id: 'page-usage',
    type: 'page',
    category: 'pages',
    group: 'Pages & Views',
    title: 'Usage',
    subtitle: 'AI token usage, provider breakdown, daily history & recent requests',
    badge: 'You > Usage',
    page: 'usage',
    icon: ChartNoAxesCombined,
    keywords: ['ai usage', 'tokens', 'openai', 'anthropic', 'gemini', 'billing', 'cost', 'model usage'],
  },
]
