import { BrainCog, Code2, Layers, MessageCircle, Palette, PhoneCall, Rocket, Shield, Sparkles, UserCheck } from 'lucide-react'

export const SETTINGS_SECTIONS_ITEMS = [
  {
    id: 'setting-profile',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Profile Settings',
    subtitle: 'Change display name, manage user credentials & identity info',
    badge: 'Settings > Profile',
    page: 'setting',
    hash: 'settings-profile',
    icon: UserCheck,
    keywords: ['profile', 'display name', 'email', 'avatar', 'user info', 'name change'],
  },
  {
    id: 'setting-themes',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Themes & UI Appearance',
    subtitle: 'Configure monochrome design tokens, border radius, density & fonts',
    badge: 'Settings > Themes',
    page: 'setting',
    hash: 'settings-themes',
    icon: Palette,
    keywords: ['themes', 'appearance', 'dark theme', 'light theme', 'typography', 'radius', 'density'],
  },
  {
    id: 'setting-appearance',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Eve UI Overrides',
    subtitle: 'Review Eve UI customizations, version history, and reset overrides',
    badge: 'Settings > Eve UI',
    page: 'setting',
    hash: 'settings-appearance',
    icon: Palette,
    keywords: ['eve ui', 'appearance', 'overrides', 'custom ui', 'version history', 'reset ui', 'eve theme'],
  },
  {
    id: 'setting-apps',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Connected Apps & Integrations',
    subtitle: 'Manage Google Calendar, Gmail, GitHub, Google Chat & Drive integrations',
    badge: 'Settings > Integrations',
    page: 'setting',
    hash: 'settings-apps',
    icon: Layers,
    keywords: ['integrations', 'google', 'github', 'gmail', 'google drive', 'google chat', 'oauth', 'ics feeds'],
  },
  {
    id: 'setting-whatsapp',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'WhatsApp Bridge Settings',
    subtitle: 'Pair WhatsApp, configure Eve auto-reply, trigger keywords, and notifications',
    badge: 'Settings > WhatsApp',
    page: 'setting',
    hash: 'settings-whatsapp',
    icon: MessageCircle,
    keywords: ['whatsapp', 'pairing', 'qr code', 'bridge', 'phone', 'service worker', 'session', 'eve keywords', 'trigger keywords', 'auto reply', 'auto-responder', 'notifications'],
  },
  {
    id: 'setting-ai-models',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'AI Models & Providers',
    subtitle: 'Configure OpenAI (GPT-5, GPT-4o), Anthropic (Claude 3.7) & Google Gemini',
    badge: 'Settings > AI Models',
    page: 'setting',
    hash: 'settings-ai-models',
    icon: Sparkles,
    keywords: ['ai models', 'openai', 'gpt-5', 'gpt-4o', 'anthropic', 'claude', 'gemini', 'api key', 'llm'],
  },
  {
    id: 'setting-eve-memory',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Eve Memory & Auto-Remember',
    subtitle: 'Toggle automatic memory saving across chats, WhatsApp, calls & schedules',
    badge: 'Settings > Eve Memory',
    page: 'setting',
    hash: 'settings-eve-memory',
    icon: BrainCog,
    keywords: ['eve memory', 'auto remember', 'auto-remember', 'memory', 'remember', 'forget', 'long-term memory', 'recall'],
  },
  {
    id: 'setting-coding',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Coding Profiles',
    subtitle: 'Sync LeetCode, Codeforces, CodeChef, and AtCoder usernames',
    badge: 'Settings > Coding',
    page: 'setting',
    hash: 'settings-coding',
    icon: Code2,
    keywords: ['leetcode username', 'codeforces handle', 'codechef', 'atcoder', 'coding sync', 'ranking'],
  },
  {
    id: 'setting-hackathons',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Hackathon Sources',
    subtitle: 'Toggle external hackathon feeds from Devpost, Unstop, MLH & Devfolio',
    badge: 'Settings > Hackathons',
    page: 'setting',
    hash: 'settings-hackathons',
    icon: Rocket,
    keywords: ['hackathon sources', 'devpost feed', 'unstop feed', 'mlh sources', 'devfolio'],
  },
  {
    id: 'setting-eve-voice',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Eve Voice & Speech Settings',
    subtitle: 'Configure STT/TTS engine, Groq Whisper, Google Cloud TTS, voices & pitch',
    badge: 'Settings > Eve Voice',
    page: 'setting',
    hash: 'settings-eve-voice',
    icon: PhoneCall,
    keywords: ['eve voice', 'tts', 'stt', 'groq whisper', 'google cloud tts', 'speech synthesis', 'mic'],
  },
  {
    id: 'setting-account',
    type: 'section',
    category: 'settings',
    group: 'Settings & Preferences',
    title: 'Account & Security',
    subtitle: 'Reset password, verify email, combine duplicate accounts, and sign out',
    badge: 'Settings > Account',
    page: 'setting',
    hash: 'settings-account',
    icon: Shield,
    keywords: ['password reset', 'security', 'combine accounts', 'verify email', 'logout', 'sign out'],
  },
]
