import {
  AppWindow,
  Blocks,
  Bot,
  Brain,
  BriefcaseBusiness,
  CalendarClock,
  CalendarDays,
  ChartNoAxesCombined,
  Code2,
  Contact,
  Files,
  FolderKanban,
  History,
  LayoutDashboard,
  LayoutTemplate,
  ListTodo,
  Mail,
  MessageCircle,
  MessageSquare,
  Palette,
  Phone,
  PhoneCall,
  Rocket,
  Settings,
  SquareTerminal,
  UserRound,
} from 'lucide-react'

export const navigationItems = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, group: 'Work' },
  { id: 'todo', label: 'Todo List', icon: ListTodo, group: 'Work' },
  { id: 'projects', label: 'Projects', icon: FolderKanban, group: 'Work' },
  { id: 'documents', label: 'Documents', icon: Files, group: 'Work' },
  { id: 'workspace', label: 'Workspace', icon: SquareTerminal, group: 'Work' },
  { id: 'studio', label: 'Studio', icon: Blocks, group: 'Studio' },
  { id: 'studio-apps', label: 'Apps', icon: AppWindow, group: 'Studio' },
  { id: 'studio-templates', label: 'Templates', icon: LayoutTemplate, group: 'Studio' },
  { id: 'eve', label: 'Chat', icon: Bot, group: 'Eve AI' },
  { id: 'eve-sessions', label: 'Chat Sessions', icon: History, group: 'Eve AI' },
  { id: 'eve-memory', label: 'Eve Memory', icon: Brain, group: 'Eve AI' },
  { id: 'eve-call', label: 'Voice & AI Call', icon: PhoneCall, group: 'Eve AI' },
  { id: 'eve-schedules', label: 'Schedules & Reminders', icon: CalendarClock, group: 'Eve AI' },
  { id: 'competitive-coding', label: 'Competitive Coding', icon: Code2, group: 'Growth' },
  { id: 'hackathons', label: 'Hackathons', icon: Rocket, group: 'Growth' },
  { id: 'jobs', label: 'Jobs', icon: BriefcaseBusiness, group: 'Growth' },
  { id: 'stats', label: 'Stats', icon: ChartNoAxesCombined, group: 'Growth' },
  { id: 'calendar', label: 'Calendar', icon: CalendarDays, group: 'Communication' },
  { id: 'mails', label: 'Mail', icon: Mail, group: 'Communication' },
  { id: 'whatsapp', label: 'WhatsApp', icon: MessageCircle, group: 'Communication' },
  { id: 'chats', label: 'Chats', icon: MessageSquare, group: 'Communication' },
  { id: 'calls', label: 'Calls', icon: Phone, group: 'Communication' },
  { id: 'contacts', label: 'Contacts', icon: Contact, group: 'Communication' },
  { id: 'profile', label: 'Profile', icon: UserRound, group: 'Account' },
  { id: 'themes', label: 'Themes', icon: Palette, group: 'Account' },
  { id: 'setting', label: 'Settings', icon: Settings, group: 'Account' },
  { id: 'usage', label: 'Usage', icon: ChartNoAxesCombined, group: 'Account' },
]

